@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET SCRIPTPATH=%~dp0
SET SCRIPTNAME=%~n0
SET SCRIPTFULLFILENAME=%~dpnx0

SET EXEDIR=%SCRIPTPATH%\..\Output\x64\Debug
SET OUTPUTDIR=HelpText

CALL :GENERATEHELPTEXT BannerText
CALL :GENERATEHELPTEXT FigLetText
CALL :GENERATEHELPTEXT PauseN
CALL :GENERATEHELPTEXT ShowDateTime
CALL :GENERATEHELPTEXT StopWatch
CALL :GENERATEHELPTEXT StopWatch list
CALL :GENERATEHELPTEXT StopWatch start
CALL :GENERATEHELPTEXT StopWatch stop
CALL :GENERATEHELPTEXT StopWatch cancel
CALL :GENERATEHELPTEXT StopWatch elapsed
CALL :GENERATEHELPTEXT StopWatch pause
CALL :GENERATEHELPTEXT StopWatch resume

CALL :GENERATEOUTPUTTEXT "FigletText-standard" FigLetText "Hello World" -n standard

POPD

GOTO :EOF


:GENERATEHELPTEXT
SET OUTPUTFILENAME=%~1.txt

IF NOT "%~2" == "" SET OUTPUTFILENAME=%~1-%~2.txt

ECHO.Generating: %~1 %~2
%EXEDIR%\%~1 %~2 --help > "%OUTPUTDIR%\%OUTPUTFILENAME%"

GOTO :EOF


:GENERATEOUTPUTTEXT
SET OUTPUTFILENAME=%~1.txt

ECHO.Generating: %~2 %~3 %~4 %~5 %~6 %~7 %~8
%EXEDIR%\%~2 %~3 %~4 %~5 %~6 %~7 %~8 > "%OUTPUTDIR%\%OUTPUTFILENAME%"

GOTO :EOF
